http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
postgres:
  pg_user: "postgres"
  pg_database: "postgres"
  pg_host: "postgresql"
  pg_port: "5432"
  pg_sslmode: "disable"
  pg_password: "1408"